In [3]:
import numpy as np 

In [24]:
mat1D = np.array([1,2,3,4,5,6,7,8,9])
print(f"Array mat1D : {mat1D}")
print(f"Array mat1D + 10 : {mat1D + 10}")
print(f"Array mat1D indeks ke 2 : {mat1D[2]}")

Array mat1D : [1 2 3 4 5 6 7 8 9]
Array mat1D + 10 : [11 12 13 14 15 16 17 18 19]
Array mat1D indeks ke 2 : 3


In [25]:
mat2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Array mat2D : {mat2D}")
print(f"Array mat2D * 10 : {mat2D * 10}")
print(f"Array mat2D indeks ke 2 : {mat2D[2]}")
print(f"Array mat2D indeks ke 2 : {mat2D[1][1] * 10}")

Array mat2D : [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array mat2D * 10 : [[10 20 30]
 [40 50 60]
 [70 80 90]]
Array mat2D indeks ke 2 : [7 8 9]
Array mat2D indeks ke 2 : 50


In [19]:
print(mat1D.shape) #mengetahui bentuk dari matriks
print(mat2D.shape)

(9,)
(3, 3)


In [20]:
print (mat1D.size) #mengetahui ukuran dari matriks
print (mat1D.size)

9
9


In [14]:
#spesial matriks
mZero = np.zeros((3,5)) #Matriks dengan nilai o
mOne = np.ones((4,4)) #Matriks dengan nilai 1
mIdentity = np.eye((5)) #Matriks diagonal 1 lainnya 0
mFull = np.full((3,3),19) #Matriks dengan nilai yang sama
mF1Random = np.random.rand(5,5) #matriks deangan nilai acak float 5 kolom
mF2Random = np.random.rand(5,5) #matriks deangan nilai float 5*f
mI1Random = np.random.randint(10,100,size=10)
mI2Random = np.random.randint(1,100,size=(4,4))
print(f"Matriks mZero :\n {mZero}")
print(f"Matriks mOne :\n {mOne}")
print(f"Matriks mIdentity :\n {mIdentity}")
print(f"Matriks mFull :\n {mFull}")
print(f"Matriks mF1Random :\n {mF1Random}")
print(f"Matriks mF2Random :\n {mF2Random}")
print(f"Matriks mI1Random :\n {mI1Random}")
print(f"Matriks mI2Random :\n {mI2Random}")

Matriks mZero :
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Matriks mOne :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Matriks mIdentity :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Matriks mFull :
 [[19 19 19]
 [19 19 19]
 [19 19 19]]
Matriks mF1Random :
 [[0.26978173 0.51599871 0.29516037 0.96451435 0.56522284]
 [0.1986599  0.91618216 0.48083026 0.59314865 0.89640942]
 [0.00483175 0.91391574 0.56369802 0.26380935 0.04523979]
 [0.31844503 0.18320811 0.14084071 0.12230679 0.99265816]
 [0.6591487  0.4278103  0.83315738 0.32603908 0.44934051]]
Matriks mF2Random :
 [[0.37063605 0.97947005 0.2233811  0.89531993 0.82069197]
 [0.99682683 0.7609097  0.83611229 0.63152321 0.1379008 ]
 [0.09585671 0.16265338 0.99553214 0.28891933 0.45103113]
 [0.99929419 0.52101694 0.20538942 0.38911289 0.59110908]
 [0.36771485 0.42729262 0.62581702 0.71326153 0.75558101]]
Matriks mI1Random :
 [35 85 61 48 30 93 15 64 66 70]
Matriks 

In [17]:
#Aritmatik array
x = np.array([1,2,3])
y = np.array([4,5,6])
r1 = np.dot(x,y)
r2 = np.add(x,y)
r3 = np.dot(x,3)
print(f"Hasil perkalian dot product : {r1}")
print(f"Hasil penjumlahan matriks:\n{r2}")
print(f"Hasil dot product dengan 3:\n{r3}")

Hasil perkalian dot product : 32
Hasil penjumlahan matriks:
[5 7 9]
Hasil dot product dengan 3:
[3 6 9]


In [22]:
#Fungsi statistik dasar
nilaiPemrograman = np.array([100,90,80,80,50,50,50,40])
nilaiMin = np.min(nilaiPemrograman)
nilaiMax = np.max(nilaiPemrograman)
nilaiMean = np.mean(nilaiPemrograman)
nilaiSum = np.sum(nilaiPemrograman)
nilaiMedian = np.median(nilaiPemrograman)
nilaiStd = np.std(nilaiPemrograman)

print(f"Nilai Pemrograman:\n{nilaiPemrograman}")
print(f"Nilai Terkecil:\n{nilaiMin}")
print(f"Nilai Terbesar:\n{nilaiMax}")
print(f"Nilai Rata-Rata:\n{nilaiMean}")
print(f"Total Nilai:\n{nilaiSum}")
print(f"Nilai Tengah:\n{nilaiMedian}")
print(f"Nilai Deviasi:\n{nilaiStd}")

#Filtering
#Mencari jumlah mahasiswa yang lulus ->nilia >50
dataLulus = nilaiPemrograman[nilaiPemrograman > 50]
print(dataLulus)
print(f"jumlah mahasiswa yang lulus:{dataLulus.size}")

Nilai Pemrograman:
[100  90  80  80  50  50  50  40]
Nilai Terkecil:
40
Nilai Terbesar:
100
Nilai Rata-Rata:
67.5
Total Nilai:
540
Nilai Tengah:
65.0
Nilai Deviasi:
21.065374432940896
[100  90  80  80]
jumlah mahasiswa yang lulus:4
